server:
  port: 9000
  servlet:
    context-path: /myAdminTemplate
spring:
  datasource:
    url: jdbc:mysql://110.40.175.203:3306/myAdminTemplate
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid: # 设置 Druid 连接池的自定义配置。然后 DruidDataSourceAutoConfigure 会自动化配置 Druid 连接池。
      min-idle: 0 # 池中维护的最小空闲连接数，默认为 0 个。
      max-active: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 8 个。
      filter:
        stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
          log-slow-sql: true # 开启慢查询记录
          slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
          merge-sql: true # SQL合并配置
      stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
        enabled: true # 是否开启 StatViewServlet
        login-username: root # 账号
        login-password: 123456 # 密码
        allow:
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/example/xiaohu/modules/mapper/xml/*Mapper.xml
  global-config:
    banner: false
swagger:
  enable: true
  production: false
  basic:
    enable: false
    username: xiaohu
    password: 123456

